import type { GuideDefinition } from "../definitions";

// Apps guides. Ported from the original seed as-is (B3 rewrites them). The closing "items" block keeps the
// links to the apps each guide was already about, now that relations derive from the body.

export const appGuides: GuideDefinition[] = [
  {
    slug: "best-free-video-players",
    title: "The Best Free Video Players",
    section: "apps",
    excerpt: "What to look for in a free video player for Windows, Mac, Linux and Android, plus the players Gametroz lists with links to official downloads.",
    metaTitle: "The Best Free Video Players | Gametroz",
    publishedAt: "2026-09-04",
    updatedAt: "2026-09-04",
    featured: true,
    sortOrder: 30,
    tags: ["video", "players", "comparison"],
    body: [
      { type: "p", text: "A good video player should open any file you throw at it, without codec packs, ads or bundled extras." },
      { type: "h2", text: "What to look for" },
      { type: "ul", items: ["Wide format support.", "Subtitle and audio track controls.", "No ads or bundled software.", "Regular updates from a trusted publisher."] },
      { type: "h2", text: "Our top pick: VLC Media Player" },
      { type: "p", text: "VLC plays almost everything, runs on every major platform and is free and open source." },
      { type: "h2", text: "If you also need to convert video" },
      { type: "p", text: "HandBrake converts videos to formats that play smoothly on phones and TVs." },
      { type: "items", title: "Apps in this guide", refs: [{ kind: "app", slug: "vlc-media-player" }, { kind: "app", slug: "handbrake" }, { kind: "app", slug: "obs-studio" }] },
    ],
  },
  {
    slug: "how-to-install-vlc",
    title: "How to Install VLC Media Player",
    section: "apps",
    excerpt: "Download VLC safely from the official VideoLAN site and install it on Windows or Mac in a few minutes, with tips to avoid modified installers.",
    metaTitle: "How to Install VLC Media Player | Gametroz",
    publishedAt: "2026-08-22",
    updatedAt: "2026-08-22",
    featured: false,
    sortOrder: 31,
    tags: ["vlc", "install", "video"],
    body: [
      { type: "p", text: "VLC is free. Always download it from the official VideoLAN website to avoid modified installers." },
      { type: "h2", text: "On Windows" },
      { type: "ol", items: ["Open the official VLC page.", "Download the Windows installer.", "Run the installer and follow the steps.", "Open a video to check it works."] },
      { type: "h2", text: "On Mac" },
      { type: "ol", items: ["Download the .dmg file.", "Drag VLC into Applications.", "Open it from Launchpad."] },
      { type: "h2", text: "Stay safe" },
      { type: "p", text: "Skip download buttons from ads and unknown mirrors. Gametroz always links to the official publisher." },
      { type: "items", title: "Apps in this guide", refs: [{ kind: "app", slug: "vlc-media-player" }] },
    ],
  },
  {
    slug: "best-free-office-suites",
    title: "The Best Free Office Suites",
    section: "apps",
    excerpt: "Write documents, build spreadsheets and manage email without paying for a license: two free programs that cover everyday office work.",
    metaTitle: "The Best Free Office Suites | Gametroz",
    publishedAt: "2026-07-12",
    updatedAt: "2026-07-12",
    featured: false,
    sortOrder: 32,
    tags: ["office", "documents", "comparison"],
    body: [
      { type: "p", text: "You do not need a paid subscription for everyday documents and spreadsheets." },
      { type: "h2", text: "LibreOffice" },
      { type: "p", text: "A complete office suite that opens and saves Microsoft Office formats." },
      { type: "h2", text: "Thunderbird" },
      { type: "p", text: "Pair it with Thunderbird for email, calendar and contacts." },
      { type: "items", title: "Apps in this guide", refs: [{ kind: "app", slug: "libreoffice" }, { kind: "app", slug: "thunderbird" }] },
    ],
  },
  {
    slug: "how-to-record-your-screen",
    title: "How to Record Your Screen for Free",
    section: "apps",
    excerpt: "Capture tutorials, gameplay or meetings for free with OBS Studio: set up your first scene, add audio and shrink the file before sharing it.",
    metaTitle: "How to Record Your Screen for Free | Gametroz",
    publishedAt: "2026-09-26",
    updatedAt: "2026-09-26",
    featured: false,
    sortOrder: 33,
    tags: ["recording", "obs", "tutorial"],
    body: [
      { type: "p", text: "OBS Studio is free and records your screen, webcam and microphone together." },
      { type: "h2", text: "Set up your first scene" },
      { type: "ol", items: ["Install OBS Studio from the official site.", "Add a Display Capture source.", "Add your microphone under Audio.", "Click Start Recording."] },
      { type: "h2", text: "Make the file smaller" },
      { type: "p", text: "Use HandBrake to convert long recordings into smaller MP4 files before sharing." },
      { type: "items", title: "Apps in this guide", refs: [{ kind: "app", slug: "obs-studio" }, { kind: "app", slug: "audacity" }, { kind: "app", slug: "handbrake" }] },
    ],
  },
];
