import {
  Archive,
  ArrowLeftRight,
  BookOpen,
  Braces,
  Calculator,
  Car,
  Code,
  Crown,
  FileText,
  Gamepad2,
  Globe,
  Image,
  Joystick,
  Laptop,
  Map,
  MessageCircle,
  Monitor,
  Palette,
  Play,
  Puzzle,
  Search,
  Shield,
  Smartphone,
  Sparkles,
  Swords,
  Terminal,
  Trophy,
  Type,
  Wrench,
  type LucideIcon,
} from "lucide-react";
import type { IconKey } from "@/types/content";

// Content stores a string key; the UI resolves it here so data never imports components.
export const contentIcons: Record<IconKey, LucideIcon> = {
  gamepad: Gamepad2,
  car: Car,
  puzzle: Puzzle,
  swords: Swords,
  trophy: Trophy,
  sparkles: Sparkles,
  map: Map,
  joystick: Joystick,
  crown: Crown,
  type: Type,
  braces: Braces,
  image: Image,
  calculator: Calculator,
  search: Search,
  file: FileText,
  arrows: ArrowLeftRight,
  play: Play,
  archive: Archive,
  palette: Palette,
  code: Code,
  shield: Shield,
  wrench: Wrench,
  message: MessageCircle,
  globe: Globe,
  monitor: Monitor,
  laptop: Laptop,
  terminal: Terminal,
  smartphone: Smartphone,
  book: BookOpen,
};
