import type { App, Category, PlatformSlug } from "@/types/content";

// Seed source data (the Phase 2 mock catalog). Only prisma/seed.ts imports this file.
// Versions and licenses are sample values,
// not verified; every record is checked against the official source in Phase 8.

export const platforms: (Category & { slug: PlatformSlug })[] = [
  { slug: "windows", name: "Windows", iconKey: "monitor", description: "Free and open-source software for Windows PCs, linked to the official download pages." },
  { slug: "mac", name: "macOS", iconKey: "laptop", description: "Useful free apps for Mac, linked to the official download pages." },
  { slug: "linux", name: "Linux", iconKey: "terminal", description: "Popular open-source apps for Linux desktops." },
  { slug: "android", name: "Android", iconKey: "smartphone", description: "Free Android apps from trusted publishers." },
  { slug: "browser", name: "Browser", iconKey: "globe", description: "Browser extensions and web apps that run where you already work." },
];

export const appCategories: Category[] = [
  { slug: "media", name: "Media", iconKey: "play", description: "Video, audio and streaming software." },
  { slug: "compression", name: "Compression", iconKey: "archive", description: "Archive and extract files." },
  { slug: "office", name: "Office", iconKey: "file", description: "Documents, spreadsheets and email." },
  { slug: "design", name: "Design", iconKey: "palette", description: "Image editing, illustration and 3D." },
  { slug: "development", name: "Development", iconKey: "code", description: "Editors and tools for developers." },
  { slug: "security", name: "Security", iconKey: "shield", description: "Passwords, privacy and protection." },
  { slug: "browsers", name: "Browsers", iconKey: "globe", description: "Web browsers and extensions." },
  { slug: "communication", name: "Communication", iconKey: "message", description: "Messaging and calls." },
];

type AppSeed = Omit<App, "category" | "iconUrl" | "lastVerifiedAt" | "featured"> & {
  category: string;
  featured?: boolean;
};

const seeds: AppSeed[] = [
  { slug: "vlc-media-player", name: "VLC Media Player", category: "media", publisher: "VideoLAN", version: "3.0.21", license: "GPL-2.0", officialWebsite: "https://www.videolan.org/vlc/", platforms: ["windows", "mac", "linux", "android"], shortDescription: "Free player for almost any video or audio format.", description: "VLC plays most multimedia files, DVDs, audio CDs and streaming protocols without extra codec packs. It is free, open source and has no ads or tracking.", features: ["Plays almost every video and audio format", "No codec packs required", "Subtitles and audio track selection", "Network streaming and conversion"], requirements: ["Windows 7 or later, macOS 10.7 or later, or a modern Linux distribution", "About 150 MB of disk space"], alternatives: ["mpv", "handbrake", "obs-studio"], tags: ["video", "player", "codecs"], featured: true },
  { slug: "7zip", name: "7-Zip", category: "compression", publisher: "Igor Pavlov", version: "24.08", license: "LGPL-2.1 (with unRAR restriction)", officialWebsite: "https://www.7-zip.org/", platforms: ["windows"], shortDescription: "File archiver with a high compression ratio.", description: "7-Zip creates and extracts archives in 7z, ZIP and many other formats. Its own 7z format offers some of the best compression available.", features: ["High compression 7z format", "Opens ZIP, RAR, TAR, ISO and more", "AES-256 encryption", "Explorer context menu integration"], requirements: ["Windows 7 or later", "Less than 5 MB of disk space"], alternatives: ["peazip", "libreoffice"], tags: ["zip", "archive", "compression"], featured: true },
  { slug: "obs-studio", name: "OBS Studio", category: "media", publisher: "OBS Project", version: "30.2", license: "GPL-2.0", officialWebsite: "https://obsproject.com/", platforms: ["windows", "mac", "linux"], shortDescription: "Record your screen and stream live.", description: "OBS Studio records and live-streams video with scenes, multiple sources and real-time audio mixing. It is used by streamers, teachers and creators.", features: ["Screen, window and webcam capture", "Scene composition with transitions", "Live streaming to major platforms", "Audio mixer with filters"], requirements: ["DirectX 11 compatible GPU on Windows", "macOS 11 or later", "4 GB of RAM recommended"], alternatives: ["vlc-media-player", "handbrake"], tags: ["recording", "streaming", "screen"], featured: true },
  { slug: "libreoffice", name: "LibreOffice", category: "office", publisher: "The Document Foundation", version: "24.8", license: "MPL-2.0", officialWebsite: "https://www.libreoffice.org/", platforms: ["windows", "mac", "linux"], shortDescription: "Free office suite for documents and spreadsheets.", description: "LibreOffice includes Writer, Calc, Impress and more. It opens and saves Microsoft Office formats and uses the open OpenDocument standard.", features: ["Word processor, spreadsheet and presentations", "Opens and saves .docx, .xlsx and .pptx", "PDF export", "Extensions and templates"], requirements: ["Windows 10 or later, macOS 10.15 or later, or Linux", "About 1.5 GB of disk space"], alternatives: ["thunderbird", "notepad-plus-plus"], tags: ["office", "documents", "spreadsheets"], featured: true },
  { slug: "gimp", name: "GIMP", category: "design", publisher: "The GIMP Team", version: "3.0", license: "GPL-3.0", officialWebsite: "https://www.gimp.org/", platforms: ["windows", "mac", "linux"], shortDescription: "Free image editor for photos and graphics.", description: "GIMP is a powerful image editor for photo retouching, image composition and graphic design, with layers, masks and plugins.", features: ["Layers, masks and blend modes", "Photo retouching tools", "Plugin and script support", "Wide file format support"], requirements: ["Windows 10 or later, macOS 11 or later, or Linux", "4 GB of RAM recommended"], alternatives: ["inkscape", "blender"], tags: ["photo", "editor", "graphics"] },
  { slug: "firefox", name: "Firefox", category: "browsers", publisher: "Mozilla", version: "131", license: "MPL-2.0", officialWebsite: "https://www.mozilla.org/firefox/", platforms: ["windows", "mac", "linux", "android"], shortDescription: "Fast, private and open-source web browser.", description: "Firefox is an independent browser with built-in tracking protection, extensions and sync across devices.", features: ["Enhanced tracking protection", "Thousands of extensions", "Sync bookmarks and passwords", "Picture-in-picture video"], requirements: ["Windows 10 or later, macOS 10.15 or later, Linux, or Android 8+"], alternatives: ["ublock-origin", "bitwarden"], tags: ["browser", "privacy", "web"] },
  { slug: "audacity", name: "Audacity", category: "media", publisher: "Audacity Team", version: "3.6", license: "GPL-3.0", officialWebsite: "https://www.audacityteam.org/", platforms: ["windows", "mac", "linux"], shortDescription: "Record and edit audio for free.", description: "Audacity is a multi-track audio editor and recorder. Cut, mix and clean up podcasts, music and voice recordings.", features: ["Multi-track recording and editing", "Noise reduction and effects", "Export to MP3, WAV and more", "Plugin support"], requirements: ["Windows 10 or later, macOS 12 or later, or Linux"], alternatives: ["obs-studio", "vlc-media-player"], tags: ["audio", "recording", "podcast"] },
  { slug: "notepad-plus-plus", name: "Notepad++", category: "development", publisher: "Don Ho", version: "8.7", license: "GPL-3.0", officialWebsite: "https://notepad-plus-plus.org/", platforms: ["windows"], shortDescription: "Lightweight code and text editor.", description: "Notepad++ is a fast source-code editor with syntax highlighting for dozens of languages, tabs and powerful search.", features: ["Syntax highlighting and folding", "Tabbed editing", "Regex search and replace", "Plugin manager"], requirements: ["Windows 7 or later"], alternatives: ["libreoffice"], tags: ["editor", "code", "text"] },
  { slug: "blender", name: "Blender", category: "design", publisher: "Blender Foundation", version: "4.2 LTS", license: "GPL-3.0", officialWebsite: "https://www.blender.org/", platforms: ["windows", "mac", "linux"], shortDescription: "Free 3D creation suite.", description: "Blender covers modeling, sculpting, animation, rendering, video editing and more in a single open-source application.", features: ["Modeling and sculpting", "Animation and rigging", "Cycles and EEVEE renderers", "Video editing"], requirements: ["64-bit quad-core CPU", "8 GB of RAM", "GPU with 2 GB of VRAM"], alternatives: ["gimp", "inkscape"], tags: ["3d", "animation", "rendering"] },
  { slug: "inkscape", name: "Inkscape", category: "design", publisher: "Inkscape Project", version: "1.4", license: "GPL-3.0", officialWebsite: "https://inkscape.org/", platforms: ["windows", "mac", "linux"], shortDescription: "Vector graphics editor for illustration and logos.", description: "Inkscape is a vector graphics editor for illustrations, icons, logos and diagrams, built around the SVG standard.", features: ["Native SVG editing", "Bezier and spiro curves", "Text on path", "PDF import and export"], requirements: ["Windows 10 or later, macOS 10.13 or later, or Linux"], alternatives: ["gimp", "blender"], tags: ["vector", "svg", "illustration"] },
  { slug: "handbrake", name: "HandBrake", category: "media", publisher: "The HandBrake Team", version: "1.8", license: "GPL-2.0", officialWebsite: "https://handbrake.fr/", platforms: ["windows", "mac", "linux"], shortDescription: "Convert video to modern formats.", description: "HandBrake converts video from nearly any format to MP4 or MKV with presets for phones, tablets and the web.", features: ["Device presets", "Batch encoding queue", "Subtitles and chapters", "H.264, H.265 and AV1"], requirements: ["Windows 10 or later, macOS 10.13 or later, or Linux"], alternatives: ["vlc-media-player", "obs-studio"], tags: ["video", "converter", "encoder"] },
  { slug: "keepassxc", name: "KeePassXC", category: "security", publisher: "KeePassXC Team", version: "2.7", license: "GPL-3.0", officialWebsite: "https://keepassxc.org/", platforms: ["windows", "mac", "linux"], shortDescription: "Offline password manager.", description: "KeePassXC stores your passwords in an encrypted database on your own device, with browser integration and a password generator.", features: ["Encrypted local database", "Browser integration", "Password generator", "TOTP support"], requirements: ["Windows 10 or later, macOS 11 or later, or Linux"], alternatives: ["bitwarden"], tags: ["passwords", "security", "offline"] },
  { slug: "thunderbird", name: "Thunderbird", category: "office", publisher: "MZLA Technologies", version: "128 ESR", license: "MPL-2.0", officialWebsite: "https://www.thunderbird.net/", platforms: ["windows", "mac", "linux", "android"], shortDescription: "Free email client with calendar.", description: "Thunderbird manages several email accounts, calendars and contacts in one place, with strong privacy defaults.", features: ["Multiple email accounts", "Built-in calendar", "Encryption with OpenPGP", "Add-ons"], requirements: ["Windows 10 or later, macOS 10.15 or later, Linux, or Android"], alternatives: ["libreoffice", "signal"], tags: ["email", "calendar", "privacy"] },
  { slug: "signal", name: "Signal", category: "communication", publisher: "Signal Messenger", version: "7.x", license: "AGPL-3.0", officialWebsite: "https://signal.org/", platforms: ["windows", "mac", "linux", "android"], shortDescription: "Private messaging with end-to-end encryption.", description: "Signal offers end-to-end encrypted messages, voice and video calls, with minimal data collection.", features: ["End-to-end encryption", "Voice and video calls", "Disappearing messages", "Desktop and mobile sync"], requirements: ["Android 5 or later", "Windows 10 or later, macOS 11 or later, or Linux"], alternatives: ["thunderbird"], tags: ["messaging", "privacy", "calls"] },
  { slug: "bitwarden", name: "Bitwarden", category: "security", publisher: "Bitwarden Inc.", version: "2024.x", license: "GPL-3.0", officialWebsite: "https://bitwarden.com/", platforms: ["windows", "mac", "linux", "android", "browser"], shortDescription: "Open-source password manager that syncs everywhere.", description: "Bitwarden stores passwords in an encrypted vault and syncs them across browsers, desktop and mobile.", features: ["Encrypted cloud vault", "Browser extensions", "Password generator", "Secure sharing"], requirements: ["Any modern browser, desktop or Android device"], alternatives: ["keepassxc"], tags: ["passwords", "security", "sync"] },
  { slug: "ublock-origin", name: "uBlock Origin", category: "browsers", publisher: "Raymond Hill", version: "1.60", license: "GPL-3.0", officialWebsite: "https://github.com/gorhill/uBlock", platforms: ["browser"], shortDescription: "Efficient content blocker for your browser.", description: "uBlock Origin is a lightweight, open-source content blocker with filter lists and low memory use.", features: ["Low memory and CPU use", "Community filter lists", "Element picker", "Per-site switches"], requirements: ["Firefox or another supported browser"], alternatives: ["firefox", "bitwarden"], tags: ["extension", "privacy", "blocker"] },
];

const categoryBySlug = new Map(appCategories.map((category) => [category.slug, category]));

export const apps: App[] = seeds.map((seed) => {
  const category = categoryBySlug.get(seed.category);
  if (!category) throw new Error(`Unknown app category: ${seed.category}`);
  return {
    ...seed,
    category: { name: category.name, slug: category.slug },
    iconUrl: `/mock/apps/${seed.slug}.svg`,
    featured: seed.featured ?? false,
    lastVerifiedAt: null,
    // Alternatives must point to apps in the catalog.
    alternatives: seed.alternatives.filter((slug) => seeds.some((other) => other.slug === slug)),
  };
});
