import type { Guide } from "@/types/content";

// Seed source data (the Phase 2 mock guides). Only prisma/seed.ts imports this file.

export const guides: Guide[] = [
  {
    slug: "how-to-compress-images",
    title: "How to Compress Images Without Losing Quality",
    excerpt: "Make your photos smaller for the web or email while keeping them sharp.",
    section: "tools",
    publishedAt: "2026-09-10",
    readingMinutes: 5,
    featured: true,
    tags: ["images", "compression", "web"],
    related: { tools: ["image-compressor", "image-resizer", "webp-to-jpg"] },
    body: [
      { type: "p", text: "Large images slow down websites and fill up mailboxes. The good news: most photos can lose half of their file size with no visible difference." },
      { type: "h2", text: "Pick the right format" },
      { type: "ul", items: ["JPG for photos with many colors.", "PNG for screenshots, logos and transparency.", "WebP when you want the smallest file and your audience uses modern browsers."] },
      { type: "h2", text: "Resize before you compress" },
      { type: "p", text: "A 4000-pixel photo shown at 1200 pixels wastes bandwidth. Resize it to the size it will be displayed, then compress it." },
      { type: "h2", text: "Compress step by step" },
      { type: "ol", items: ["Open the Image Compressor.", "Drop your images.", "Start at 80% quality and compare.", "Download the result."] },
      { type: "p", text: "Keep the original file in case you need to edit it again later." },
    ],
  },
  {
    slug: "best-free-video-players",
    title: "The Best Free Video Players",
    excerpt: "Our picks for playing any video file on Windows, Mac, Linux and Android.",
    section: "apps",
    publishedAt: "2026-09-04",
    readingMinutes: 6,
    featured: true,
    tags: ["video", "players", "comparison"],
    related: { apps: ["vlc-media-player", "handbrake", "obs-studio"] },
    body: [
      { type: "p", text: "A good video player should open any file you throw at it, without codec packs, ads or bundled extras." },
      { type: "h2", text: "What to look for" },
      { type: "ul", items: ["Wide format support.", "Subtitle and audio track controls.", "No ads or bundled software.", "Regular updates from a trusted publisher."] },
      { type: "h2", text: "Our top pick: VLC Media Player" },
      { type: "p", text: "VLC plays almost everything, runs on every major platform and is free and open source." },
      { type: "h2", text: "If you also need to convert video" },
      { type: "p", text: "HandBrake converts videos to formats that play smoothly on phones and TVs." },
    ],
  },
  {
    slug: "how-to-install-vlc",
    title: "How to Install VLC Media Player",
    excerpt: "Download VLC safely from the official site and install it in a few minutes.",
    section: "apps",
    publishedAt: "2026-08-22",
    readingMinutes: 4,
    featured: false,
    tags: ["vlc", "install", "video"],
    related: { apps: ["vlc-media-player"] },
    body: [
      { type: "p", text: "VLC is free. Always download it from the official VideoLAN website to avoid modified installers." },
      { type: "h2", text: "On Windows" },
      { type: "ol", items: ["Open the official VLC page.", "Download the Windows installer.", "Run the installer and follow the steps.", "Open a video to check it works."] },
      { type: "h2", text: "On Mac" },
      { type: "ol", items: ["Download the .dmg file.", "Drag VLC into Applications.", "Open it from Launchpad."] },
      { type: "h2", text: "Stay safe" },
      { type: "p", text: "Skip download buttons from ads and unknown mirrors. Gametroz always links to the official publisher." },
    ],
  },
  {
    slug: "how-to-format-json",
    title: "How to Format and Validate JSON",
    excerpt: "Turn messy JSON into readable, valid data in seconds.",
    section: "tools",
    publishedAt: "2026-09-18",
    readingMinutes: 4,
    featured: false,
    tags: ["json", "developer", "format"],
    related: { tools: ["json-formatter", "base64-encoder-decoder"] },
    body: [
      { type: "p", text: "Minified JSON is great for machines and hard for people. Formatting it adds indentation so you can read and debug it." },
      { type: "h2", text: "Common JSON errors" },
      { type: "ul", items: ["Trailing commas after the last item.", "Single quotes instead of double quotes.", "Unquoted property names."] },
      { type: "h2", text: "Format it" },
      { type: "ol", items: ["Paste your JSON into the JSON Formatter.", "Click Format.", "Fix any error it reports.", "Copy the clean output."] },
    ],
  },
  {
    slug: "how-to-calculate-percentages",
    title: "How to Calculate Percentages Quickly",
    excerpt: "Three formulas that cover discounts, tips and growth.",
    section: "tools",
    publishedAt: "2026-07-30",
    readingMinutes: 3,
    featured: false,
    tags: ["math", "percentage", "calculator"],
    related: { tools: ["percentage-calculator", "discount-calculator"] },
    body: [
      { type: "p", text: "Most everyday percentage questions use one of three formulas." },
      { type: "h2", text: "X% of a number" },
      { type: "p", text: "Multiply the number by X and divide by 100. For example, 20% of 50 is 10." },
      { type: "h2", text: "What percent is A of B" },
      { type: "p", text: "Divide A by B and multiply by 100. For example, 15 of 60 is 25%." },
      { type: "h2", text: "Percentage change" },
      { type: "p", text: "Subtract the old value from the new one, divide by the old value and multiply by 100." },
    ],
  },
  {
    slug: "best-racing-games-online",
    title: "The Best Racing Games to Play Online",
    excerpt: "From neon drifts to motorbike stunts: our favorite racing games right now.",
    section: "games",
    publishedAt: "2026-09-21",
    readingMinutes: 5,
    featured: true,
    tags: ["racing", "cars", "ranking"],
    related: { games: ["neon-drift", "moto-stunts", "kart-rally", "turbo-lane"] },
    body: [
      { type: "p", text: "Browser racing games have come a long way. These are the ones we keep coming back to." },
      { type: "h2", text: "Neon Drift" },
      { type: "p", text: "Long drifts fill your boost meter. Perfect if you like style over pure speed." },
      { type: "h2", text: "Moto Stunts" },
      { type: "p", text: "Physics-based bike stunts with satisfying flips and tricky landings." },
      { type: "h2", text: "Kart Rally" },
      { type: "p", text: "Items, shortcuts and eight colorful tracks. Great for short sessions." },
    ],
  },
  {
    slug: "how-to-play-games-in-fullscreen",
    title: "How to Play Browser Games in Fullscreen",
    excerpt: "Get a bigger view and fewer distractions on desktop and mobile.",
    section: "games",
    publishedAt: "2026-08-14",
    readingMinutes: 3,
    featured: false,
    tags: ["fullscreen", "tips", "mobile"],
    related: { games: ["sky-raiders", "tower-guard"] },
    body: [
      { type: "p", text: "Fullscreen mode makes games easier to play and hides everything else on the page." },
      { type: "h2", text: "On desktop" },
      { type: "ol", items: ["Open a game.", "Click the Fullscreen button under the player.", "Press Esc to exit."] },
      { type: "h2", text: "On mobile" },
      { type: "p", text: "Rotate your phone for landscape games, then tap Fullscreen. Some phones also hide the address bar when you scroll." },
    ],
  },
  {
    slug: "puzzle-games-for-beginners",
    title: "Puzzle Games for Beginners",
    excerpt: "Easy-to-learn puzzle games that still keep your brain busy.",
    section: "games",
    publishedAt: "2026-06-26",
    readingMinutes: 4,
    featured: false,
    tags: ["puzzle", "beginners", "brain"],
    related: { games: ["block-cascade", "pipe-flow", "sudoku-daily", "word-grid"] },
    body: [
      { type: "p", text: "New to puzzle games? Start with these. They teach one rule at a time." },
      { type: "h2", text: "Start simple" },
      { type: "ul", items: ["Block Cascade: line-clearing with gentle speed.", "Pipe Flow: rotate pieces to connect a path.", "Word Grid: find words at your own pace."] },
      { type: "h2", text: "Level up" },
      { type: "p", text: "Once you are comfortable, try Sudoku Daily on medium difficulty." },
    ],
  },
  {
    slug: "best-free-office-suites",
    title: "The Best Free Office Suites",
    excerpt: "Write documents, build spreadsheets and manage email without paying for a license.",
    section: "apps",
    publishedAt: "2026-07-12",
    readingMinutes: 5,
    featured: false,
    tags: ["office", "documents", "comparison"],
    related: { apps: ["libreoffice", "thunderbird"] },
    body: [
      { type: "p", text: "You do not need a paid subscription for everyday documents and spreadsheets." },
      { type: "h2", text: "LibreOffice" },
      { type: "p", text: "A complete office suite that opens and saves Microsoft Office formats." },
      { type: "h2", text: "Thunderbird" },
      { type: "p", text: "Pair it with Thunderbird for email, calendar and contacts." },
    ],
  },
  {
    slug: "how-to-record-your-screen",
    title: "How to Record Your Screen for Free",
    excerpt: "Capture tutorials, gameplay or meetings with OBS Studio.",
    section: "apps",
    publishedAt: "2026-09-26",
    readingMinutes: 6,
    featured: false,
    tags: ["recording", "obs", "tutorial"],
    related: { apps: ["obs-studio", "audacity", "handbrake"] },
    body: [
      { type: "p", text: "OBS Studio is free and records your screen, webcam and microphone together." },
      { type: "h2", text: "Set up your first scene" },
      { type: "ol", items: ["Install OBS Studio from the official site.", "Add a Display Capture source.", "Add your microphone under Audio.", "Click Start Recording."] },
      { type: "h2", text: "Make the file smaller" },
      { type: "p", text: "Use HandBrake to convert long recordings into smaller MP4 files before sharing." },
    ],
  },
];
